exports.CS_FOLD = 'CS_FOLD';
exports.CS_CHECK = 'CS_CHECK';
exports.CS_CALL = 'CS_CALL';
exports.CS_RAISE = 'CS_RAISE';
exports.WINNER = 'WINNER';
exports.CS_FETCH_LOBBY_INFO = 'CS_FETCH_LOBBY_INFO';
exports.SC_RECEIVE_LOBBY_INFO = 'SC_RECEIVE_LOBBY_INFO';
exports.SC_PLAYERS_UPDATED = 'SC_PLAYERS_UPDATED';
exports.CS_JOIN_TABLE = 'CS_JOIN_TABLE';
exports.SC_TABLE_JOINED = 'SC_TABLE_JOINED';
exports.CS_LEAVE_TABLE = 'CS_LEAVE_TABLE';
exports.SC_TABLE_LEFT = 'SC_TABLE_LEFT';
exports.SC_TABLES_UPDATED = 'SC_TABLES_UPDATED';
exports.SC_TABLE_UPDATED = 'SC_TABLE_UPDATED';
exports.TABLE_MESSAGE = 'TABLE_MESSAGE';
exports.CS_REBUY = 'CS_REBUY';
exports.CS_SIT_DOWN = 'CS_SIT_DOWN';
exports.CS_STAND_UP = 'CS_STAND_UP';
exports.SITTING_OUT = 'SITTING_OUT';
exports.SITTING_IN = 'SITTING_IN';
exports.CS_DISCONNECT = 'CS_DISCONNECT';
exports.CS_LOBBY_CONNECT = 'CS_LOBBY_CONNECT';
exports.CS_LOBBY_DISCONNECT = 'CS_LOBBY_DISCONNECT';
exports.SC_LOBBY_CONNECTED = 'SC_LOBBY_CONNECTED';
exports.SC_LOBBY_DISCONNECTED = 'SC_LOBBY_DISCONNECTED';
exports.CS_LOBBY_CHAT = 'CS_LOBBY_CHAT';
exports.SC_LOBBY_CHAT = 'SC_LOBBY_CHAT';

// Multi-game / lobby
exports.CS_FILL_BOTS = 'CS_FILL_BOTS';
exports.CS_FILL_TOURNAMENT_BOTS = 'CS_FILL_TOURNAMENT_BOTS';
exports.SC_TOURNAMENTS_UPDATED = 'SC_TOURNAMENTS_UPDATED';
exports.CS_REGISTER_TOURNAMENT = 'CS_REGISTER_TOURNAMENT';
exports.CS_START_TOURNAMENT = 'CS_START_TOURNAMENT';
exports.SC_TOURNAMENT_UPDATED = 'SC_TOURNAMENT_UPDATED';
exports.SC_TOURNAMENT_STARTED = 'SC_TOURNAMENT_STARTED';

// Blackjack
exports.CS_BJ_BET = 'CS_BJ_BET';
exports.CS_BJ_HIT = 'CS_BJ_HIT';
exports.CS_BJ_STAND = 'CS_BJ_STAND';
exports.CS_BJ_DOUBLE = 'CS_BJ_DOUBLE';
exports.CS_BJ_DEAL = 'CS_BJ_DEAL';

// PROTO token bridge
exports.CS_PROTO_DEPOSIT = 'CS_PROTO_DEPOSIT';
exports.CS_PROTO_WITHDRAW = 'CS_PROTO_WITHDRAW';
exports.SC_PROTO_BANKROLL = 'SC_PROTO_BANKROLL';
